name: pawpals
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^13.2.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1

  # Maps and location (Leaflet)
  flutter_map: ^6.1.0 # For Leaflet maps
  geolocator: ^11.0.0 # Keep for location services
  http: ^1.2.1 # For making HTTP requests to backend API and Nominatim

  # Calendar
  table_calendar: ^3.1.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  image_picker: ^1.0.7
  password_strength_checker: ^1.2.2
  shared_preferences: ^2.2.2 # For storing auth token

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/